site_name: Risco 5S
site_author: Julio Nunes Avelar
site_description: RISC-V Simulator with RV32IM implementation, built during a few days off.
repo_name: Risco-5S
repo_url: https://github.com/JN513/Risco-5S
site_url: https://jn513.github.io/Risco-5S/
copyright: CC BY-SA 4.0 - Julio Nunes Avelar
nav:
  - Home: index.md
theme:
  name: material
  #language: pt-BR
  logo: imgs/risco5.jpeg
  favicon: imgs/risco5.jpeg
  highlightjs: true
  features:
      - toc.integrate
      - navigation.tabs
      - navigation.expand
      #- navigation.instant
      #- navigation.instant.progress
      - content.code.copy
      - content.code.select
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  #- pdf-export
  #- offline
  - search:
      lang:
        - en
        - pt
extra:
  social:
    - icon: fontawesome/brands/gitlab 
      link: https://gitlab.com/jn513
    - icon: fontawesome/brands/github 
      link: https://github.com/JN513/Risco-5S

markdown_extensions:
  - attr_list
  - md_in_html